# Generated by Django 4.0.4 on 2022-05-14 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_updated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
