# Generated by Django 4.0.4 on 2022-05-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
    ]
